server:
  port: 8181
spring:
  application:
    name: Ebeddedkafka
  kafka:
    client-id: test-client-id
    bootstrap-servers: localhost:29092
    producer:
      acks: all
    consumer:
      group-id: test-group-id
      client-id: test-client-id
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 10